DROP TABLE MEMBER;

-- 회원가입 한 멤버
CREATE TABLE TB_MEMBER(
    USER_NO NUMBER PRIMARY KEY,
    USER_ID VARCHAR2(20) NOT NULL UNIQUE,
    USER_PWD VARCHAR2(20) NOT NULL,
    USER_NAME VARCHAR2(15) NOT NULL,
    USER_GRADE CHAR(9) NOT NULL CHECK(USER_GRADE IN ('관리자', '회원')),
    USER_POINT NUMBER DEFAULT 0
);

-- 조명기 리스트
CREATE TABLE TB_LIGHTING(
    LIT
);

-- 라인 리스트 (합칠 것인가?)
CREATE TABLE TB_LINE(
);

-- 프로덕션 리스트
CREATE TABLE TB_PRODUCTION(
);

-- 프로덕션 별 장비 수량 저장하는 중계테이블
CREATE TABLE TB_INOUTLIST(
);

-- 프로덕션 별 역할 멤버 저장하는 중계테이블
CREATE TABLE TB_MEM_ROLL(
);


CREATE SEQUENCE SEQ_MEMNO
NOCACHE;
