-- 1) 연결할 두 컬럼명이 다른 경우 (EMPLOYEE : DEPT_CODE / DEPARTMENT : DEPT_ID)
-- 전체 사원들의 사번, 사원명, 부서 코드, 부서명을 조회
SELECT EMP_ID, EMP_NAME, DEPT_CODE, DEPT_TITLE
FROM EMPLOYEE E, DEPARTMENT D
WHERE E.DEPT_CODE = D.DEPT_ID;

-- 2) 연결할 두 컬럼명이 같은 경우 (EMPLOYEE : JOB_CODE / JOB : JOB_CODE)
-- 전체 사원들의 사번, 사원명, 직급 코드, 직급명 조회
SELECT EMP_ID, EMP_NAME, E.JOB_CODE, JOB_NAME
FROM EMPLOYEE E, JOB J
WHERE E.JOB_CODE = J.JOB_CODE;

SELECT EMP_ID, EMP_NAME, JOB_CODE, JOB_TITLE
FROM EMPLOYEE E, JOB J
WHERE E.JOB_CODE = J.JOB_CODE; --오류

SELECT EMP_ID, EMP_NAME, E.JOB_CODE, JOB_TITLE
FROM EMPLOYEE E, JOB J
WHERE JOB_CODE = JOB_CODE; --오류


-- 1. 부서가 인사관리부인 사원들의 사번, 이름, 보너스를 조회
SELECT EMP_ID, EMP_NAME, BONUS
FROM EMPLOYEE, DEPARTMENT
WHERE DEPT_CODE = DEPT_ID
AND DEPT_TITLE = '인사관리부';

-- 2. DEPARTMENT와 LOCATION 테이블을 참고하여 전체 부서의 부서 코드, 부서명, 지역 코드, 지역명 조회
SELECT DEPT_ID, DEPT_TITLE, LOCATION_ID, LOCAL_NAME
FROM DEPARTMENT, LOCATION
WHERE LOCATION_ID = LOCAL_CODE;

SELECT EMP_NAME, DEPT_TITLE, SALARY, SALARY * 12
FROM EMPLOYEE, DEPARTMENT
WHERE DEPT_CODE = DEPT_ID(+);



















SELECT EMP_NAME, EMP_NO, DEPT_CODE, SALARY

FROM EMPLOYEE

WHERE (DEPT_CODE = 'D9' OR DEPT_CODE = 'D6')

AND SALARY >= 3000000

AND SUBSTR(EMP_NO, 8, 1) = 1

AND EMAIL LIKE '___|_%' ESCAPE '|'

AND BONUS IS NOT NULL;

SELECT *

FROM EMPLOYEE

WHERE BONUS IS NULL

AND MANAGER_ID IS NOT NULL;

CREATE USER SAMPLE IDENTIFIED BY 1234;
GRANT RESOURCE, CONNECT TO SAMPLE;




SELECT DEPT_CODE, SUM(SALARY) 합계, FLOOR(AVG(SALARY)) 평균, COUNT(*) 인원수

FROM EMPLOYEE

GROUP BY DEPT_CODE
HAVING FLOOR(AVG(SALARY)) > 2800000
ORDER BY DEPT_CODE ASC;

SELECT ROWNUM, EMP_NAME, SALARY
FROM (SELECT EMP_NAME, SALARY
        FROM EMPLOYEE
    ORDER BY SALARY DESC)
WHERE ROWNUM <= 3
AND SALARY IS NOT NULL;