-- 조건 구문 순서
-- CREATE TABLE 테이블명 (
--      컬럼명 자료형 DEFAULT 디폴트값 CONSTRAINT 제약조건명 제약조건 ON DELETE 삭제옵션
-- );


CREATE TABLE LHT_DEVICE (
    LHT_NO NUMBER CONSTRAINT LHT_PK_NO PRIMARY KEY,
    LHT_NAME VARCHAR2(40) CONSTRAINT LHT_NN_UQ_NAME NOT NULL UNIQUE,
    LHT_MNFT VARCHAR2(40),
    LHT_QTY NUMBER DEFAULT 0 CONSTRAINT LHT_NN_QTY NOT NULL,
    LHT_LAMP VARCHAR2(10) CONSTRAINT LHT_CK_SPS CHECK(LHT_LAMP IN ('lamp', 'LED'))
);

CREATE TABLE PRODUCTION (
    PDC_NO NUMBER CONSTRAINT PDC_PK_NO PRIMARY KEY,
    PDC_NAME VARCHAR2(50) CONSTRAINT PDC_NN_NAME NOT NULL,
    PDC_THEATRE VARCHAR2(40),
    PDC_OPENING DATE,
    PDC_CLOSING DATE
);

SELECT * FROM LHT_DEVICE;
SELECT * FROM PRODUCTION;

INSERT INTO LHT_DEVICE
VALUES (1, 'Sola Spot Pro CMY', 'HighEnd', 30, 'LED');

INSERT INTO LHT_DEVICE
VALUES (2, 'Aura', 'Martin', 40, 'LED');

INSERT INTO LHT_DEVICE
VALUES (3, 'Auros', 'Ayrton', 50, 'lamp');

INSERT INTO LHT_DEVICE (LHT_NO, LHT_NAME, LHT_MNFT, LHT_QTY)
VALUES (4, 'F101', 'ADB', 30);

INSERT INTO LHT_DEVICE (LHT_NO, LHT_NAME)
VALUES (5, 'PAR64');

INSERT INTO LHT_DEVICE (LHT_NO, LHT_NAME, LHT_MNFT)
VALUES (6, 'Infinity Spot M', 'Martin');

-- 수량 변경
UPDATE LHT_DEVICE
SET LHT_QTY = '20'
WHERE LHT_NAME = 'Infinity Spot M';

-- 와트 추가



-----------------------------------------------------------------------------------
DROP TABLE EMP_02;
CREATE TABLE EMP_02(
    EMP_ID NUMBER,
    EMP_NAME VARCHAR2(20),
    DEPT_TITLE VARCHAR2(20)
);

SELECT * FROM EMP_02;

INSERT INTO EMP_02 (SELECT EMP_ID, EMP_NAME, DEPT_TITLE
                    FROM EMPLOYEE
                    LEFT JOIN DEPARTMENT ON (DEPT_CODE = DEPT_ID));
--/ 서브쿼리로 테이블을 인서트 하면 VALUES는 써주지 않아도 됨
--/ DEPT_CODE가 없는 사원들의 정보까지 전체를 다 가져오고 싶은 거니까 LEFT JOIN

CREATE TABLE EMP_DEPTS
AS (SELECT EMP_ID, EMP_NAME, DEPT_CODE, HIRE_DATE
    FROM EMPLOYEE
    WHERE 1 = 0);

CREATE TABLE EMP_MANAGERS
AS (SELECT EMP_ID, EMP_NAME, MANAGER_ID
    FROM EMPLOYEE
    WHERE 1 = 0);
    
-- 부서코드가 D1인 사원들의 사번, 이름, 부서코드, 입사일, 사수 사번
SELECT EMP_ID, EMP_NAME, DEPT_CODE, HIRE_DATE, MANAGER_ID
FROM EMPLOYEE
WHERE DEPT_CODE = 'D1';

INSERT ALL
    INTO EMP_DEPTS VALUES (EMP_ID, EMP_NAME, DEPT_CODE, HIRE_DATE)
    INTO EMP_MANAGERS VALUES (EMP_ID, EMP_NAME, MANAGER_ID)
        (SELECT EMP_ID, EMP_NAME, DEPT_CODE, HIRE_DATE, MANAGER_ID
         FROM EMPLOYEE
         WHERE DEPT_CODE = 'D1');
    
SELECT * FROM EMP_DEPTS;
SELECT * FROM EMP_MANAGERS;

ROLLBACK;

INSERT ALL
    INTO EMP_DEPTS VALUES (EMP_ID, EMP_NAME, DEPT_CODE, HIRE_DATE) --/ 뭘 넣을지는 정해줘야 함
    INTO EMP_MANAGERS VALUES (EMP_ID, EMP_NAME, MANAGER_ID)
        (SELECT * --/ 이것도 됨
         FROM EMPLOYEE
         WHERE DEPT_CODE = 'D1');
         



CREATE TABLE DEPT_TABLES
AS (SELECT * FROM DEPARTMENT);
SELECT * FROM DEPT_TABLES;

-- D9 부서의 부서명을 '전략기획팀으로 변경'
UPDATE DEPT_TABLES
SET DEPT_TITLE = '전략기획팀'
WHERE DEPT_ID = 'D9';

CREATE TABLE EMP_SALARYS
AS (SELECT EMP_ID, EMP_NAME, DEPT_CODE, SALARY, BONUS
    FROM EMPLOYEE);
    
SELECT * FROM EMP_SALARYS;

-- 노옹철 사원의 급여를 100만원으로 변경
UPDATE EMP_SALARYS
SET SALARY = 1000000
WHERE EMP_NAME = '노옹철';
-- 선동일 사원의 급여를 700만원, 보너스를 0.2로 변경
UPDATE EMP_SALARYS
SET SALARY = 7000000,
    BONUS = 0.2
WHERE EMP_NAME = '선동일';
-- 전체 사원의 급여를 기존 급여에서 10프로 인상된 금액으로 변경(기존 급여 * 1.1)
UPDATE EMP_SALARYS
SET SALARY = SALARY * 1.1;

-- 방명수 사원의 급여와 보너스 값을 유재식 사원의 급여와 보너스 값으로 변경
UPDATE EMP_SALARYS
SET (SALARY, BONUS) = (SELECT SALARY, BONUS
                        FROM EMP_SALARYS
                        WHERE EMP_NAME = '유재식')
WHERE EMP_NAME = '방명수';

-- ASIA 지역에서 근무하는 사원들의 보너스 값을 0.3으로 변경
UPDATE EMP_SALARYS
SET BONUS = 0.3
WHERE EMP_ID IN (SELECT EMP_ID
                 FROM EMPLOYEE
                 JOIN DEPARTMENT ON (DEPT_CODE = DEPT_ID)
                 JOIN LOCATION ON (LOCATION_ID = LOCAL_CODE)
                 WHERE LOCAL_NAME LIKE 'ASIA%');
                 

DELETE FROM EMPLOYEE;
SELECT * FROM EMPLOYEE;
--/ 테이블 자체의 정보가 삭제되는 것이 아님
--/ 테이블 안에 있는 데이터, 컬럼값만 삭제

ROLLBACK;

INSERT INTO EMPLOYEE
VALUES(999, '이지수', '980724-0000000', 'JULYLEE0724@NAVER.COM', NULL, 'D9', 'J8', 3000000, 0.2, NULL, SYSDATE, NULL, 'N');

DELETE FROM EMPLOYEE
WHERE EMP_ID = 999;

---------------------------------------------------------------------------
CREATE TABLE DEPT_TABLE
AS (SELECT *
    FROM DEPARTMENT);
    
SELECT * FROM DEPT_TABLE;

ALTER TABLE DEPT_TABLE ADD CNAME VARCHAR2(20);
ALTER TABLE DEPT_TABLE MODIFY DEPT_ID VARCHAR2(5);
ALTER TABLE DEPT_TABLE MODIFY DEPT_ID CHAR(3);

ALTER TABLE DEPT_TABLE
    MODIFY DEPT_TITLE VARCHAR2(40)
    MODIFY CNAME DEFAULT '미국';
    
ALTER TABLE DEPT_TABLE DROP COLUMN CNAME;