SELECT *
FROM ROLE_SYS_PRIVS;

CREATE TABLE EMP_TEST_01
AS (SELECT EMP_ID, EMP_NAME
    FROM EMPLOYEE);

SELECT * FROM EMP_TEST_01;
-- 이건 테이블 생성이니까 트랜잭션에 포함되는 행위가 아님
-- INSERT, UPDATE, DELETE만 해당
ROLLBACK;

UPDATE EMP_TEST_01
SET EMP_ID = 900
WHERE EMP_NAME = '선동일';

SAVEPOINT SP1;

DELETE FROM EMP_TEST_01
WHERE EMP_ID = 900;

ROLLBACK TO SP1;

COMMIT;


CREATE OR REPLACE VIEW VW_EMPLOYEE_TEST
AS SELECT EMP_ID, EMP_NAME, DEPT_TITLE
   FROM EMPLOYEE
   JOIN DEPARTMENT ON (DEPT_CODE = DEPT_ID);
   
SELECT * FROM VW_EMPLOYEE_TEST;

SELECT *
FROM VW_EMPLOYEE_TEST
WHERE DEPT_TITLE = '인사관리부';

CREATE OR REPLACE VIEW VW_EMPLOYEE_TEST1
AS SELECT EMP_ID, EMP_NAME, DEPT_TITLE
   FROM EMPLOYEE
   JOIN DEPARTMENT ON (DEPT_CODE = DEPT_ID)
   WHERE EMP_ID < 210;
   
SELECT * FROM VW_EMPLOYEE_TEST1;

CREATE OR REPLACE VIEW VW_EMPLOYEE_TEST2 (사번, 사원명, 부서명, 성별)
AS SELECT EMP_ID, EMP_NAME, DEPT_TITLE,
          DECODE(SUBSTR(EMP_NO, 8, 1), '1', '남', '2', '여')
   FROM EMPLOYEE
   JOIN DEPARTMENT ON (DEPT_CODE = DEPT_ID);
   
SELECT * FROM VW_EMPLOYEE_TEST2;


-----------------------------------------------------------------------------------



CREATE SEQUENCE SEQ_EMPTEST;
SELECT * FROM USER_SEQUENCES;

CREATE SEQUENCE SEQ_EMPTEST1
START WITH 10
INCREMENT BY 10
MAXVALUE 50
MINVALUE 30 --/ START WITH cannot be less than MINVALUE
CYCLE
CACHE 25;

CREATE SEQUENCE SEQ_EMPTEST1
START WITH 10
INCREMENT BY 10
MAXVALUE 50
MINVALUE 0
CYCLE
CACHE 5;

CREATE SEQUENCE SEQ_EMPTEST2
START WITH 10
INCREMENT BY 10
MAXVALUE 50
MINVALUE 0
CYCLE
CACHE 5;

SELECT * FROM USER_SEQUENCES;

SELECT SEQ_EMPTEST1.NEXTVAL FROM DUAL;

CREATE TABLE SEQTEST(
    TEST_ID NUMBER PRIMARY KEY,
    TEST_NAME VARCHAR2(20)
);

SELECT * FROM SEQTEST;

INSERT INTO SEQTEST
VALUES(SEQ_EMPTEST1.NEXTVAL, '전은지'); -- 20
INSERT INTO SEQTEST
VALUES(SEQ_EMPTEST1.NEXTVAL, '이지수'); -- 30
INSERT INTO SEQTEST
VALUES(SEQ_EMPTEST1.NEXTVAL, '전은지'); -- 40
INSERT INTO SEQTEST
VALUES(SEQ_EMPTEST1.NEXTVAL, '이지수'); -- 50
INSERT INTO SEQTEST
VALUES(SEQ_EMPTEST1.NEXTVAL, '전은지'); -- 0 (MINVALUE값)
INSERT INTO SEQTEST
VALUES(SEQ_EMPTEST1.NEXTVAL, '이지수'); -- 10
INSERT INTO SEQTEST
VALUES(SEQ_EMPTEST1.NEXTVAL, '전은지'); --unique constraint (KH.SYS_C007111) violated
--/ PRIMARY KEY로 설정해놔서 중복될 수 없다는 규칙에 어긋나 오류남

CREATE TABLE SEQTEST2(
    TEST_ID NUMBER,
    TEST_NAME VARCHAR2(20)
);

SELECT * FROM SEQTEST2;

INSERT INTO SEQTEST2
VALUES(SEQ_EMPTEST2.NEXTVAL, '전은지'); -- 
INSERT INTO SEQTEST2
VALUES(SEQ_EMPTEST2.NEXTVAL, '이지수'); -- 30
INSERT INTO SEQTEST2
VALUES(SEQ_EMPTEST2.NEXTVAL, '전은지'); -- 40
INSERT INTO SEQTEST2
VALUES(SEQ_EMPTEST2.NEXTVAL, '이지수'); -- 50
INSERT INTO SEQTEST2
VALUES(SEQ_EMPTEST2.NEXTVAL, '전은지'); -- 0 (MINVALUE값)
INSERT INTO SEQTEST2
VALUES(SEQ_EMPTEST2.NEXTVAL, '이지수'); -- 10
INSERT INTO SEQTEST2
VALUES(SEQ_EMPTEST2.NEXTVAL, '*'); -- 중복 허용되므로 그냥 ID 30에 이름 *인 행 생성
