-- 1)
SELECT DEPARTMENT_NAME AS "학과명", CATEGORY "계열"
FROM TB_DEPARTMENT;

-- 2)
SELECT DEPARTMENT_NAME || '의 정원은 ' || CAPACITY || '명 입니다.' AS "학과별 정원"
FROM TB_DEPARTMENT;

-- 3)
SELECT STUDENT_NAME
FROM TB_DEPARTMENT
JOIN TB_STUDENT USING (DEPARTMENT_NO)
WHERE DEPARTMENT_NAME = '국어국문학과'
AND SUBSTR(STUDENT_SSN, 8, 1) = '2'
AND ABSENCE_YN = 'Y';
-- 답지 쪽이 덜 무겁나?
-- 그럴듯...
-- 아닌가...
-- 일반적으로 서브쿼리 없이 JOIN문만으로 작성하는 게 성능적으로 빠를 수 있으나,
-- 테이블 구조에 따라 다를 수 있으므로 실제 쿼리 속도를 비교해보는 것이 좋음
-- 서브쿼리를 사용하면 결과값을 찾아낼 때까지 매번 서브쿼리를 실행, 속도가 JOIN보다 느릴 수밖에 없음

-- JOIN 시킬 땐 필요한 정보 순대로 차례대로 JOIN하자

-- 답지 예시
SELECT STUDENT_NAME
FROM TB_STUDENT
    LEFT JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
WHERE DEPARTMENT_NAME = '국어국문학과'
      AND SUBSTR(STUDENT_SSN, 8, 1) = 2
      AND ABSENCE_YN = 'Y';

-- 4)
SELECT STUDENT_NAME
FROM TB_STUDENT
WHERE STUDENT_NO IN ('A513079', 'A513090', 'A513091', 'A513110', 'A513119');

-- 답지 예시
SELECT STUDENT_NAME
FROM TB_STUDENT
WHERE STUDENT_NO IN ('A513079', 'A513090', 'A513091', 'A513110', 'A513119')
ORDER BY 1 DESC;

-- 5)
SELECT DEPARTMENT_NAME, CATEGORY
FROM TB_DEPARTMENT
WHERE CAPACITY BETWEEN 20 AND 30;

-- 6)
SELECT PROFESSOR_NAME
FROM TB_PROFESSOR
WHERE DEPARTMENT_NO IS NULL;

-- 7)
SELECT STUDENT_NAME
FROM TB_STUDENT
WHERE DEPARTMENT_NO IS NULL;

-- 8)
SELECT CLASS_NO
FROM TB_CLASS
WHERE PREATTENDING_CLASS_NO IS NOT NULL;

-- 9)
SELECT DISTINCT CATEGORY
FROM TB_DEPARTMENT;
-- 답지 예시
SELECT DISTINCT CATEGORY
FROM TB_DEPARTMENT
ORDER BY 1;

-- 10)
SELECT STUDENT_NO, STUDENT_NAME, STUDENT_SSN
FROM TB_STUDENT
WHERE EXTRACT(YEAR FROM ENTRANCE_DATE) = '2002'
AND STUDENT_ADDRESS LIKE '%전주%'
AND ABSENCE_YN = 'N';