-- 1)
SELECT STUDENT_NO AS "학번", STUDENT_NAME AS "이름", ENTRANCE_DATE AS "입학년도"
FROM TB_STUDENT
WHERE DEPARTMENT_NO = '002'
ORDER BY ENTRANCE_DATE;

-- 2)
SELECT PROFESSOR_NAME, PROFESSOR_SSN
FROM TB_PROFESSOR
WHERE NOT PROFESSOR_NAME LIKE '___';

-- 3)
SELECT PROFESSOR_NAME AS "교수 이름", 
        ABS(EXTRACT(YEAR FROM SYSDATE) - EXTRACT(YEAR FROM TO_DATE(SUBSTR(PROFESSOR_SSN, 1, 2), 'YY'))) AS "나이"
FROM TB_PROFESSOR
ORDER BY "나이";

-- 4)
SELECT SUBSTR(PROFESSOR_NAME, 2) AS "이름"
FROM TB_PROFESSOR;

-- 5)
SELECT STUDENT_NO, STUDENT_NAME
FROM TB_STUDENT
WHERE SUBSTR(STUDENT_SSN, 1, 2) + 20 >= EXTRACT(YEAR FROM ENTRANCE_DATE);

-- 6)
SELECT TO_DATE(201225)
FROM DUAL;
--> 금요일

-- 7)

SELECT TO_DATE('99/10/11', 'YY/MM/DD') FROM DUAL; --> 2099
SELECT TO_DATE('49/10/11', 'YY/MM/DD') FROM DUAL; --> 2049
SELECT TO_DATE('99/10/11', 'RR/MM/DD') FROM DUAL; --> 1999
SELECT TO_DATE('49/10/11', 'RR/MM/DD') FROM DUAL; --> 1949

-- 8)
SELECT STUDENT_NO, STUDENT_NAME
FROM TB_STUDENT
WHERE NOT STUDENT_NO LIKE 'A%';

-- 9)
SELECT ROUND(AVG(POINT), 1) AS "평점"
FROM TB_GRADE
GROUP BY STUDENT_NO
HAVING STUDENT_NO = 'A517178';

-- 10)
SELECT DEPARTMENT_NO AS "학과번호", COUNT(*) AS "학생수(명)"
FROM TB_STUDENT
GROUP BY DEPARTMENT_NO
ORDER BY DEPARTMENT_NO;

-- 11)
SELECT COUNT(*)
FROM TB_STUDENT
GROUP BY COACH_PROFESSOR_NO
HAVING COACH_PROFESSOR_NO IS NULL;

-- 12)
--SELECT SUBSTR(TERM_NO, 1, 4) AS "년도", ROUND(AVG(POINT), 1) AS "년도 별 평점"
--FROM TB_GRADE
--GROUP BY STUDENT_NO
--HAVING SUBSTR(TERM_NO, 1, 4)
--ORDER BY 년도;

SELECT SUBSTR(TERM_NO, 1, 4) AS "년도", ROUND(AVG(POINT), 1) AS "년도 별 평점"
FROM TB_GRADE
WHERE STUDENT_NO = 'A112113'
GROUP BY SUBSTR(TERM_NO, 1, 4)
ORDER BY 년도;

-- 13) 
SELECT DEPARTMENT_NO, NVL(COUNT(*), 0)
FROM TB_STUDENT
WHERE ABSENCE_YN = 'Y'
GROUP BY DEPARTMENT_NO
ORDER BY DEPARTMENT_NO;

SELECT DEPARTMENT_NO, NVL(휴학생수, 0)
FROM (SELECT DEPARTMENT_NO, COUNT(*) AS "휴학생수"
        FROM TB_STUDENT
    WHERE ABSENCE_YN = 'Y'
    GROUP BY DEPARTMENT_NO
    ORDER BY DEPARTMENT_NO)
LEFT JOIN TB_DEPARTMENT USING (DEPARTMENT_NO);

SELECT DEPARTMENT_NO, COUNT(*)
FROM TB_STUDENT
WHERE ABSENCE_YN = 'Y'
AND DEPARTMENT_NO = '002'
GROUP BY DEPARTMENT_NO
ORDER BY DEPARTMENT_NO;

SELECT DEPARTMENT_NO, NVL(COACH_PROFESSOR_NO, 0)
FROM TB_STUDENT
ORDER BY DEPARTMENT_NO;

-- 14)
SELECT STUDENT_NAME, COUNT(*)
FROM TB_STUDENT
GROUP BY STUDENT_NAME
HAVING COUNT(*) >= 2
ORDER BY STUDENT_NAME;

-- 15)
SELECT TERM_NO, POINT
FROM TB_GRADE
WHERE STUDENT_NO = 'A112113';

SELECT SUBSTR(TERM_NO, 1, 4) AS "년도", AVG(POINT) AS "평점"
FROM TB_GRADE
WHERE STUDENT_NO = 'A112113'
GROUP BY SUBSTR(TERM_NO, 1, 4)
ORDER BY SUBSTR(TERM_NO, 1, 4);

