-- 1)
INSERT INTO TB_CLASS_TYPE
VALUES(01, '전공필수');
INSERT INTO TB_CLASS_TYPE
VALUES(02, '전공선택');
INSERT INTO TB_CLASS_TYPE
VALUES(03, '교양필수');
INSERT INTO TB_CLASS_TYPE
VALUES(04, '교양선택');
INSERT INTO TB_CLASS_TYPE
VALUES(05, '논문지도');

-- 2)
CREATE TABLE TB_STU_INFO
AS (SELECT STUDENT_NO, STUDENT_NAME, STUDENT_ADDRESS
    FROM TB_STUDENT);
    
SELECT * FROM TB_STU_INFO;

-- 3)
DROP TABLE TB_국어국문학과;

CREATE TABLE TB_국어국문학과
AS (SELECT STUDENT_NO, STUDENT_NAME,
    EXTRACT(YEAR FROM TO_DATE(SUBSTR(STUDENT_SSN, 1, 2), 'RRRR')) AS "출생년도", NVL(PROFESSOR_NAME, '지도교수 없음')--/ 함수가 들어가면 별칭 지정 해줘야 하는 건가?
    FROM TB_STUDENT S
    LEFT JOIN TB_PROFESSOR P ON (S.COACH_PROFESSOR_NO = P.PROFESSOR_NO)
    JOIN TB_DEPARTMENT D ON(S.DEPARTMENT_NO = D.DEPARTMENT_NO)
    WHERE DEPARTMENT_NAME = '국어국문학과');
-- 서브쿼리 SELECT 절에 산술식/함수식이 기술된 경우에는 반드시 별칭을 지정해야 함

CREATE TABLE TB_국어국문학과
AS (SELECT STUDENT_NO, STUDENT_NAME,
    EXTRACT(YEAR FROM TO_DATE(SUBSTR(STUDENT_SSN, 1, 2), 'RRRR')) AS "출생년도", NVL(PROFESSOR_NAME, '지도교수 없음') AS "지도교수"
    FROM TB_STUDENT S
    LEFT JOIN TB_PROFESSOR P ON (S.COACH_PROFESSOR_NO = P.PROFESSOR_NO)
    JOIN TB_DEPARTMENT D ON(S.DEPARTMENT_NO = D.DEPARTMENT_NO)
    WHERE DEPARTMENT_NAME = '국어국문학과');
    
SELECT * FROM TB_국어국문학과;

-- 4)
UPDATE TB_DEPARTMENT
SET CAPACITY = ROUND(CAPACITY * 1.1);

SELECT DEPARTMENT_NAME, CAPACITY
FROM TB_DEPARTMENT;

ROLLBACK;

-- 5)
UPDATE TB_STUDENT
SET STUDENT_ADDRESS = '서울시 종로구 숭인동 181-21'
WHERE STUDENT_NO = 'A413042';

SELECT STUDENT_NO, STUDENT_ADDRESS
FROM TB_STUDENT
WHERE STUDENT_NO = 'A413042';

-- 6)
UPDATE TB_STUDENT
SET STUDENT_SSN = SUBSTR(STUDENT_SSN, 1, 6);

SELECT STUDENT_SSN
FROM TB_STUDENT;

-- 7)
--UPDATE TB_GRADE
--SET POINT = 3.5
--WHERE TERM_NO = '200501'
--AND STUDENT_NO = (SELECT STUDENT_NO
--                    FROM TB_STUDENT
--                    JOIN TB_DEPARTMENT USING (DEPARTMENT_NO)
--                    WHERE STUDENT_NAME = '김명훈'
--                    AND DEPARTMENT_NAME = '의학과');
--
--SELECT STUDENT_NO, TERM_NO, POINT
--FROM TB_GRADE
--WHERE TERM_NO = '200501'
--AND STUDENT_NO = (SELECT STUDENT_NO
--                    FROM TB_STUDENT
--                    WHERE STUDENT_NAME = '김명훈');

UPDATE TB_GRADE
SET POINT = 3.5
WHERE TERM_NO = '200501'
AND (CLASS_NO, STUDENT_NO) = (SELECT CLASS_NO, STUDENT_NO
                             FROM TB_STUDENT
                             JOIN TB_DEPARTMENT USING (DEPARTMENT_NO)
                             JOIN TB_CLASS USING (DEPARTMENT_NO)
                             WHERE STUDENT_NAME = '김명훈'
                             AND DEPARTMENT_NAME = '의학과'
                             AND CLASS_NAME = '피부생리학');
                             
ROLLBACK;

SELECT STUDENT_NO, TERM_NO, POINT
FROM TB_GRADE
WHERE TERM_NO = '200501'
AND (CLASS_NO, STUDENT_NO) = (SELECT CLASS_NO, STUDENT_NO
                             FROM TB_STUDENT
                             JOIN TB_DEPARTMENT USING (DEPARTMENT_NO)
                             JOIN TB_CLASS USING (DEPARTMENT_NO)
                             WHERE STUDENT_NAME = '김명훈'
                             AND DEPARTMENT_NAME = '의학과'
                             AND CLASS_NAME = '피부생리학');
                             
-- 8)
DELETE 
FROM TB_GRADE
WHERE STUDENT_NO IN (SELECT STUDENT_NO
                    FROM TB_STUDENT
                    WHERE ABSENCE_YN = 'Y');
ROLLBACK;

SELECT * FROM TB_GRADE;